name: scripting
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  beautiful_soup_dart: ^0.3.0
  dio: ^4.0.6
  logger: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
